### ISSUE TITLE
Netplus failed to build with error C1083: Cannot open include file: 'netp/core/compiler/msvc__NETP_ARCH_STR_.hpp' and C1189: #error:  "Platform not supported!" with MSVC on windows

### ISSUE THREAD

**Issue by YangYang129** [netplus/netplus#10]
Netplus failed to build with error C1083: Cannot open include file: 'netp/core/compiler/msvc__NETP_ARCH_STR_.hpp' and C1189: #error:  "Platform not supported!" with MSVC on windows. It can reproduces on version https://github.com/netplus/netplus/commit/5db9e3ab4d370cbd9b9f105b0dce64100d0ab7bc. Could you please help look at this issue? Thank you very much

**Environment**
Compiler version: VS2019 (16.11.9)
Operating system: Windows server 2019

Steps to reproduce:
1. open VS2019 x64 tools command
2. git clone https://github.com/netplus/netplus F:\netplus
3. cd F:\netplus\projects\cmake
4. "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
5. mkdir build_arm64 & cd build_arm64
6.  cmake -G "Visual Studio 16 2019" -A arm64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 ..
7. msbuild /m /p:Platform=arm64 /p:Configuration=Release netplus.sln /t:Rebuild

**Build.log:**
[msbuild.log](https://github.com/netplus/netplus/files/8115510/msbuild.log)

**Error info:**
5>F:\netplus\projects\cmake\..\..\include\netp/core/compiler.hpp(98,10): fatal error C1083: Cannot open include file: 'netp/core/compiler/msvc__NETP_ARCH_STR_.hpp': No such file or directory (d:\a01\_work\3\s\src\vctools\Compiler\CxxFE\sl\p1\c\p0prepro.c:1968) [F:\netplus\projects\cmake\build_arm64\netplus.vcxproj]
5>F:\netplus\3rd\stack_walker\StackWalker.cpp(1194,1): fatal error C1189: #error:  "Platform not supported!" [F:\netplus\projects\cmake\build_arm64\netplus.vcxproj]

**Comment by ffproxy** [comment]
StackWalker is not available on msvc&arm platform, I've disabled it. could you please checkout the latest commit to take a try ?

**Comment by netplus** [comment]
StackWalker is not available on msvc&arm platform, I've disabled it. could you please checkout the latest commit to take a try ?

**Comment by YangYang129** [comment]
Hi @netplus , I try to rebuild in the latest commit https://github.com/netplus/netplus/commit/c2081aa7a42b05e31890697d3137ac2574d493de, these two error still can be repro.
[msbuild.log](https://github.com/netplus/netplus/files/8130973/msbuild.log)

**Comment by netplus** [comment]
@YangYang129 The latest commit includes the support for arm/arm64 on msvc platform. I've done a successful compile by building (https://github.com/netplus/netplus/blob/main/projects/msvc/netplus.vcxproj) directly. I'm not sure whether the cmake proj works properly , Could you take a try then ?

**Comment by YangYang129** [comment]
@netplus I try re-build netplus, display "LINK : fatal error LNK1561: entry point must be defined"
**Steps to reproduce:**
1. open VS2019 x64 tools command
2. git clone https://github.com/netplus/netplus F:\netplus
3. F:\netplus\projects\msvc
4. mkdir build_amr64 & cd mkdir build_amr64
5. "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
6. set INCLUDE=F:\netplus\3rd\c-ares\c-ares-1.17.2\include;%INCLUDE%
7. set INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um;%INCLUDE%
8. set INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared;%INCLUDE%
9. set INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include;%INCLUDE%
10. set INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt;%INCLUDE%
11. set INCLUDE=F:\netplus\include;%INCLUDE%
12. msbuild /m /p:Platform=arm64 /p:Configuration=Release ../netplus.sln /p:useenv=true /t:Rebuild

**Build.log:**
[msbuild.log](https://github.com/netplus/netplus/files/8152152/msbuild.log)

**Error info:**
LINK : fatal error LNK1561: entry point must be defined [F:\netplus\projects\msvc\netplus.vcxproj]

**Comment by netplus** [comment]
Netplus is a static lib, so it's ok to get ": unresolved external symbol WinMain", We have to our own int main(int argc, char** argv) {} to link against Netplus lib.

**Comment by netplus** [comment]
@YangYang129 I suggest you write a x86 arch based application first, then compile it for a arm based arch. This shall simplify the understanding. 

For a x86 arch based netplus app, we have lot's of example under test folder.

**Comment by YangYang129** [comment]
@netplus I have build pass on latest version https://github.com/netplus/netplus/commit/d01cd39eed7e88ad938fce6e19e155a4e3c86eb4. Thank you very much
