### ISSUE TITLE
Netplus failed to build due to "fatal error C1083: Cannot open include file: 'ares_build.h': No such file or directory" on x86 and x64 configuration with MSVC on windows

### ISSUE THREAD

**Issue by rachelhe123** [netplus/netplus#11]
**Describe the bug**
Netplus failed to build due to "fatal error C1083: Cannot open include file: 'ares_build.h': No such file or directory" on x86 and x64 configuration with MSVC on windows. Could you please help look at this issue or provide some workarounds? Thanks in advance.

**To Reproduce**
1. git clone https://github.com/netplus/netplus F:\gitP\musescore\MuseScore
2. mkdir F:\gitP\netplus\netplus\projects\cmake\build_amd64
3. cd F:\gitP\netplus\netplus\projects\cmake\build_amd64
4. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
5. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 .. 2>&1
6. msbuild /m /p:Platform=x64 /p:Configuration=Release netplus.sln /t:Rebuild 2>&1

**Error Message**
"F:\gitP\netplus\netplus\projects\cmake\build_amd64\netplus.sln" (Rebuild target) (1) ->
       "F:\gitP\netplus\netplus\projects\cmake\build_amd64\netplus.vcxproj.metaproj" (Rebuild target) (3) ->
       "F:\gitP\netplus\netplus\projects\cmake\build_amd64\netplus.vcxproj" (Rebuild target) (5) ->
       (ClCompile target) ->
         F:\gitP\netplus\netplus\3rd\c-ares\c-ares-1.18.1\src\lib\ares_setup.h(83,10): fatal error C1083: Cannot open include file: 'ares_build.h': No such file or directory (D:\a01\_work\2\s\src\vctools\Compiler\CxxFE\sl\p1\c\p0prepro.c:1934) [F:\gitP\netplus\netplus\projects\cmake\build_amd64\netplus.vcxproj]

    11 Warning(s)
    1 Error(s)

**Expected behavior**
Build successfully.

**Setup**
VS 2019 + Windows Server 2019

**Additional context**
[build.log](https://github.com/netplus/netplus/files/8956065/build.log)
log

**Comment by netplus** [comment]
A fix commit was done on main branch, Could you please take a try ?

**Comment by rachelhe123** [comment]
Thanks for your attention, I tried on new commit [d871a1d](https://github.com/netplus/netplus/commit/d871a1da040eaf073cb433e83fe77ad62cb2eea3), it passed now. So close this issue as Fixed.

**Comment by rachelhe123** [comment]
Thanks for your attention, I tried on new commit [d871a1d](https://github.com/netplus/netplus/commit/d871a1da040eaf073cb433e83fe77ad62cb2eea3), it passed now. So close this issue as Fixed.
