### ISSUE TITLE
Netplus failed to build with error C2065: 'SO_MARK' on windows with MSVC

### ISSUE THREAD

**Issue by spacelg** [netplus/netplus#17]
Hi,

Netplus failed to build with error C2065: 'SO_MARK' on windows with MSVC, it can be reproduced on latest main commit dcdb97c on main branch. Could you please help look at this issue? Thanks in advance.

**Steps to reproduce the behavior:**
1. git clone https://github.com/netplus/netplus C:\gitP\netplus\netplus
2. Open a VS2022 x64 cmd && cd C:\gitP\netplus\netplus\projects\cmake && mkdir build_amd64 && cd build_amd64
3. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 ..
4. msbuild /m /p:Platform=x64 /p:Configuration=Release netplus.sln /t:Rebuild

**Error Log:**
[Build.log](https://github.com/user-attachments/files/16974598/Build.log)

**ErrorMessage:**
5>C:\gitP\netplus\netplus\src\socket_func.cpp(94,44): error C2065: 'SO_MARK': undeclared identifier [C:\gitP\netplus\netplus\projects\cmake\build_amd64\netplus.vcxproj]

**Comment by netplus** [comment]
Could you please take a try on the latest commit, it should fixed.

**Comment by netplus** [comment]
it should be fixed, so I'll close this issue.
